package frontend.peer;

import backend.peer.Peer;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rajat
 */
public class PeerGUI extends javax.swing.JFrame {

    /**
     * Creates new form peerGUI
     */
    public PeerGUI(Peer peer) {
        this.peer = peer;
        jFC = new javax.swing.JFileChooser();
        initComponents();
        dtm = (DefaultTableModel) fileTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        trackerPanel = new javax.swing.JPanel();
        trackerLabel = new javax.swing.JLabel();
        trackerButton = new javax.swing.JButton();
        trackerField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        sendingPanel = new javax.swing.JPanel();
        chooseFileButton = new javax.swing.JButton();
        sendingLogScroll = new javax.swing.JScrollPane();
        sendingLog = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        receivingPanel = new javax.swing.JPanel();
        receiveField = new javax.swing.JTextField();
        receive = new javax.swing.JButton();
        receivingScroll = new javax.swing.JScrollPane();
        receivingLog = new javax.swing.JTextArea();
        receivingHeading = new javax.swing.JLabel();
        terminateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P2P File Share");
        setLocation(new java.awt.Point(320, 180));

        trackerPanel.setBackground(new java.awt.Color(255, 255, 255));

        trackerLabel.setText(" Enter Tracker's IP Address:");

        trackerButton.setText("Submit");
        trackerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackerButtonActionPerformed(evt);
            }
        });

        trackerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackerFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trackerPanelLayout = new javax.swing.GroupLayout(trackerPanel);
        trackerPanel.setLayout(trackerPanelLayout);
        trackerPanelLayout.setHorizontalGroup(
            trackerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trackerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trackerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(trackerLabel)
                    .addGroup(trackerPanelLayout.createSequentialGroup()
                        .addComponent(trackerField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trackerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        trackerPanelLayout.setVerticalGroup(
            trackerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trackerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trackerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(trackerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trackerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trackerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sendingPanel.setBackground(new java.awt.Color(255, 255, 255));

        chooseFileButton.setText("Choose File to Share");
        chooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileButtonActionPerformed(evt);
            }
        });

        sendingLog.setColumns(20);
        sendingLog.setFont(new java.awt.Font("Droid Sans", 0, 8)); // NOI18N
        sendingLog.setRows(5);
        sendingLogScroll.setViewportView(sendingLog);

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Filename", "Filepath"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fileTable.setGridColor(new java.awt.Color(255, 255, 255));
        fileTable.setOpaque(false);
        fileTable.setRowMargin(0);
        fileTable.setRowSelectionAllowed(false);
        fileTable.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(fileTable);
        if (fileTable.getColumnModel().getColumnCount() > 0) {
            fileTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setText("Sending log:");

        javax.swing.GroupLayout sendingPanelLayout = new javax.swing.GroupLayout(sendingPanel);
        sendingPanel.setLayout(sendingPanelLayout);
        sendingPanelLayout.setHorizontalGroup(
            sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(sendingPanelLayout.createSequentialGroup()
                        .addGroup(sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sendingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(sendingLogScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sendingPanelLayout.setVerticalGroup(
            sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseFileButton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sendingLogScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        receivingPanel.setBackground(new java.awt.Color(255, 255, 255));

        receive.setText("Receive");
        receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveActionPerformed(evt);
            }
        });

        receivingLog.setColumns(20);
        receivingLog.setFont(new java.awt.Font("Droid Sans", 0, 8)); // NOI18N
        receivingLog.setRows(2);
        receivingScroll.setViewportView(receivingLog);

        receivingHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receivingHeading.setText("Enter the file name to receive:");

        terminateButton.setText("Terminate");
        terminateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Receiving log:");

        javax.swing.GroupLayout receivingPanelLayout = new javax.swing.GroupLayout(receivingPanel);
        receivingPanel.setLayout(receivingPanelLayout);
        receivingPanelLayout.setHorizontalGroup(
            receivingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receivingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receivingPanelLayout.createSequentialGroup()
                        .addComponent(receiveField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(receivingScroll, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(receivingPanelLayout.createSequentialGroup()
                        .addGroup(receivingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terminateButton, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2))
                        .addGap(212, 212, 212))
                    .addGroup(receivingPanelLayout.createSequentialGroup()
                        .addComponent(receivingHeading)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        receivingPanelLayout.setVerticalGroup(
            receivingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receivingHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receivingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(receive)
                    .addComponent(receiveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receivingScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminateButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trackerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receivingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(trackerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sendingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(receivingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveActionPerformed
        peer.setFileRequired(receiveField.getText());
    }//GEN-LAST:event_receiveActionPerformed

    private void trackerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackerFieldActionPerformed

    private void terminateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateButtonActionPerformed

        peer.terminate();
        this.dispose();
    }//GEN-LAST:event_terminateButtonActionPerformed

    private void trackerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackerButtonActionPerformed
        peer.setTrackerInetAddress(trackerField.getText());
        peer.connectToTracker();
        peer.communicateWithTracker();
        trackerField.setEditable(false);
    }//GEN-LAST:event_trackerButtonActionPerformed

    private void chooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileButtonActionPerformed

        jFC.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        int option = jFC.showOpenDialog(PeerGUI.this);

        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFC.getSelectedFile();
            peer.addToFileList(selectedFile);
            System.out.println(peer.getPathMap().toString());
            int row = peer.getPathMap().size() - 1;
            
            if(row > 3) {
                dtm.addRow(new String[] {selectedFile.getName(), selectedFile.getAbsolutePath()});
            }
            dtm.setValueAt(selectedFile.getName(), row, 0);
            dtm.setValueAt(selectedFile.getAbsolutePath(), row, 1);
        }
    }//GEN-LAST:event_chooseFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PeerGUI pgui = new PeerGUI(new Peer());
                pgui.setVisible(true);
            }
        });
    }

    private final Peer peer;
    private final javax.swing.JFileChooser jFC;
    private final DefaultTableModel dtm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JTable fileTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton receive;
    private javax.swing.JTextField receiveField;
    private javax.swing.JLabel receivingHeading;
    private javax.swing.JTextArea receivingLog;
    private javax.swing.JPanel receivingPanel;
    private javax.swing.JScrollPane receivingScroll;
    private javax.swing.JTextArea sendingLog;
    private javax.swing.JScrollPane sendingLogScroll;
    private javax.swing.JPanel sendingPanel;
    private javax.swing.JButton terminateButton;
    private javax.swing.JButton trackerButton;
    private javax.swing.JTextField trackerField;
    private javax.swing.JLabel trackerLabel;
    private javax.swing.JPanel trackerPanel;
    // End of variables declaration//GEN-END:variables
}
